# Generated by Django 3.2.12 on 2022-02-16 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='demoapp.tab'),
        ),
        migrations.AlterField(
            model_name='param',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param', to='demoapp.group'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab', to='demoapp.page'),
        ),
    ]
